name: flutter_drawer_menu
description: An easy to use drawer menu in flutter and can used for navigation
version: 0.1.4
homepage: https://github.com/rododendron88/flutter_drawer_menu
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
